#!/usr/bin/env python
import sys
import os

#converts between "chrX" and "X" formats. Inverts the format based on the input.

if(len(sys.argv)!=4):
	print "USAGE: python convChr [originalBed] [ChrCol] [outputBed]"
else:
	
	#params
	oBedFile = sys.argv[1]
	chrCol = int(sys.argv[2])
	outputBedFile = sys.argv[3]

	#figure out format
	chrFormat = False
	testf = open(oBedFile,'r')
	line = testf.readline()
	lineParts = line.split('\t')
	if("chr" in lineParts[chrCol]):
		chrFormat = True
	testf.close()

	#generate output file
	fin = open(oBedFile,'r')
	fout = open(outputBedFile,'w')
	for line in fin:
		lineParts = line.split('\t')
		if(chrFormat):
			lineParts[chrCol] = lineParts[chrCol].replace('chr','') 
		else:
			lineParts[chrCol] = 'chr' + lineParts[chrCol]
		newLine = '\t'.join(lineParts).strip()
		fout.write(newLine + '\n')
	fin.close()
	fout.close()
	
	#check
	if(chrFormat):
		print 'Converted '  +oBedFile + ' from ChrX to X format and wrote to: ' + outputBedFile
	else:
		print 'Converted ' + oBedFile +  ' from X to ChrX format and wrote to: ' + outputBedFile 
