#!/usr/bin/env python
import sys
import os

if(len(sys.argv)!=4):
	print "USAGE: python countIndels.py [File] [RefCol] [AltCol]"
else:

	#params
	fileName = sys.argv[1]
	refCol = int(sys.argv[2])
	altCol = int(sys.argv[3])

	#open file
	fin = open(fileName,'r')
	numIndels = 0
	for line in fin:
		lineParts = line.split('\t')
		if(len(lineParts[refCol].strip())!=1):
			numIndels = numIndels + 1
		elif(len(lineParts[altCol].strip())!=1):
			numIndels = numIndels + 1
	
	#print
	print 'Number of indels in ' + fileName + ': ' + str(numIndels)
