#!/usr/bin/python
import sys
import os

if(len(sys.argv)!=5):
	print "USAGE: python filterIndels.py [File] [RefCol] [AltCol] [outFile]"
else:

	#params
	fileName = sys.argv[1]
	refCol = int(sys.argv[2])
	altCol = int(sys.argv[3])
	outFileName = sys.argv[4]

	#open file
	fin = open(fileName,'r')
	fout = open(outFileName,'w')
	numIndels = 0
	nonIndels = 0
	tcnt=0
	header = fin.readline().strip()
	fout.write(header + '\n')
	for line in fin:
		lineParts = line.split('\t')
		isIndel = False
		if(len(lineParts[refCol].strip())!=1):
			numIndels = numIndels + 1
			isIndel = True
		elif(len(lineParts[altCol].strip())!=1):
			numIndels = numIndels + 1
			isIndel = True
		if(not isIndel):
			nonIndels = nonIndels + 1
			fout.write(line)
		tcnt = tcnt  + 1
	fout.close()
	fin.close()
			
	#print
	print 'Number of indels in ' + fileName + ': ' + str(numIndels)
	print 'Number of nonindels in ' + fileName + ': ' + str(nonIndels)
	print 'Number of total lines in ' + fileName + ': ' + str(tcnt)
