#!/usr/bin/python
import sys
import os

if(len(sys.argv)!=3):
	print "USAGE: python fixIndels.py [OriginalFile] [IndelFile]"
else:
	
	#open file pointers
	oFile = open(sys.argv[1],'r')
	indelFile = open(sys.argv[2],'r')
	
	for oLine in oFile:
		indelLine = indelFile.readline()
		oLineParts = oLine.split('\t')
		indelLineParts = indelLine.split('\t')
		oLineHash = '\t'.join(oLineParts[0:5])
		indelLineHash = '\t'.join(indelLineParts[0:5])
		if(oLineHash != indelLineHash):
			oLineParts[0:5] = indelLineParts[0:5]
		newLine = '\t'.join(oLineParts)	
		print newLine[:-1]
