#!/usr/bin/python
import sys
import os

if(len(sys.argv)!=3):
	print "USAGE: python genTestBed.py [BedFile] [WindowSize (Odd Number)]"
else:
	
	#extract params
	bedFile = sys.argv[1]
	win_size = int(sys.argv[2])
	if(win_size%2==0):
		print 'win_size must be odd.'
		sys.exit(1)
	half_window_size = int((win_size-1)/2)
	
	#loop
	f = open(bedFile,'r')
	for line in f:
		lineParts = line.split('\t')
		chrs = lineParts[0]
		start = int(lineParts[1])
		ref = lineParts[3].strip()
		alt = lineParts[4].strip()
		print chrs + '\t' + str(start-half_window_size-1) + '\t' + str(start+half_window_size) + '\t' + ref + '\t' + alt
