#!/usr/bin/python
import os
import sys

if(len(sys.argv)<3):
	print "USAGE: python stackFiles.py [OutputFile] [file 1] [file2]...[fileN] where all files have same header."
	sys.exit(1)

#output file
outfile = sys.argv[1]

#extract params 1 by 1
headerO = ''
outf = open(outfile,'w')
FirstFile=True
for i in range(2,len(sys.argv)):
	
	#open file
	f = open(sys.argv[i],'r')
	header = f.readline()
	if(FirstFile):
		outf.write(header)
		FirstFile = False
		headerO = header
	if(headerO!='' and header!=headerO):
		print 'WARNING:HEADERS DO NOT MATCH.'
		sys.exit(1)
	else:
		for line in f:
			outf.write(line.strip() + '\n')
		f.close()
outf.close()
